# Base configs
baseurl: "https://eevangel.github.io/ArtGallery"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Personal Art Gallery by Edgar Evangelista"
subtitle: "Paintings and Drawings"
author: "Edgar Evangelista"
header:
 title: "Art Portfolio"
 subtitle: "by Edgar Evangelista"
footer:
 name: "Hi, I'm Edgar Evangelista"
 bio: "I am a programmer and artist from California. Here is the drawing and paintings I've created."
 github: "This art gallery Jekyll theme is modified from Ram Swaroop's Photography @ <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/edgar.evangelista"
  linkedin: "https://in.linkedin.com/in/eevangel"
